In [28]:
from config import *
import requests
import plotly
import matplotlib.pyplot as plt
import yfinance as yf
import os
import sys
import pandas as pd
from scipy.stats import pearsonr
from datetime import datetime
from dateutil.relativedelta import relativedelta

https://aroussi.com/post/python-yahoo-finance

# Global Vars

In [10]:
blue_chip_stocks = [
    'DIS',
    'AAPL',
    'AXP',
    'BAC',
    'C',
    'CAT',
    'MCD',
    'MMM',
    'WMT',
    'GS',
    'MSFT'
]

In [32]:
DT_STATIC = datetime(2023,9,29)
DT_3YR_PRIOR = DT_STATIC - relativedelta(years=3)
# DT_STATIC_STR = datetime.strftime(DT_STATIC, '%Y-%m-%d')

In [33]:
DT_3YR_PRIOR

datetime.datetime(2020, 9, 29, 0, 0)

# Functions / Classes

In [39]:
class TickerObj:
    def __init__(self, name):
        self.ticker = name
        self.obj = yf.Ticker(name)
        self.data = self.obj.history(start=DT_3YR_PRIOR, end=DT_STATIC)
        self.info = self.obj.info

# Import Data

In [67]:
df_spy = TickerObj('SPY').data

In [68]:
df_spy['DailyPercentageChange'] = (df_spy['Close'] - df_spy.shift(1)['Close'])/df_spy.shift(1)['Close']

In [69]:
for i in [5, 10, 20, 50]:
    df_spy[f'Ma{i}Day'] = df_spy.shift(1)['Close'].rolling(i).mean()

In [70]:
df_spy

,Open,High,Low,Close,Volume,Dividends,Stock Splits,DailyPercentageChange,Ma5Day,Ma10Day,Ma20Day,Ma50Day
Date,,,,,,,,,,,,
2020-09-29,319.393698,320.158770,317.146260,317.863525,51304000,0.0,0,NaN,NaN,NaN,NaN,NaN
2020-09-30,318.552134,323.525190,318.351308,320.273590,104081100,0.0,0,0.007582,NaN,NaN,NaN,NaN
2020-10-01,322.951306,323.955466,320.388283,322.329681,88698700,0.0,0,0.006420,NaN,NaN,NaN,NaN
2020-10-02,317.222826,322.301066,316.735075,319.269409,89431100,0.0,0,-0.009494,NaN,NaN,NaN,NaN
2020-10-05,321.392507,325.122284,321.344701,324.931030,45713100,0.0,0,0.017733,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2023-09-22,432.450012,434.100006,429.989990,430.420013,100757900,0.0,0,-0.002249,439.948004,442.870770,443.733267,445.722371
2023-09-25,429.170013,432.269989,428.720001,432.230011,70874500,0.0,0,0.004205,437.358008,441.517371,443.486549,445.371175
2023-09-26,429.089996,429.820007,425.019989,425.880005,96168400,0.0,0,-0.014691,435.078009,440.052997,443.176874,445.061759
2023-09-27,427.089996,427.670013,422.290009,426.049988,104705800,0.0,0,0.000399,431.712012,438.198761,442.410687,444.594253
2023-09-28,425.480011,430.250000,424.869995,428.519989,92258300,0.0,0,0.005797,429.194006,436.309705,441.334125,444.063382

In [57]:
df_spy.shift(1)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,DailyPercentageChange
Date,,,,,,,,
2020-09-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-30,319.393760,320.158832,317.146320,317.863586,51304000.0,0.0,0.0,NaN
2020-10-01,318.552195,323.525251,318.351369,320.273651,104081100.0,0.0,0.0,0.007582
2020-10-02,322.951398,323.955558,320.388374,322.329773,88698700.0,0.0,0.0,0.006420
2020-10-05,317.222826,322.301066,316.735075,319.269409,89431100.0,0.0,0.0,-0.009495
...,...,...,...,...,...,...,...,...
2023-09-22,435.700012,435.970001,431.230011,431.390015,103976100.0,0.0,0.0,-0.016528
2023-09-25,432.450012,434.100006,429.989990,430.420013,100757900.0,0.0,0.0,-0.002249
2023-09-26,429.170013,432.269989,428.720001,432.230011,70874500.0,0.0,0.0,0.004205
2023-09-27,429.089996,429.820007,425.019989,425.880005,96168400.0,0.0,0.0,-0.014691
2023-09-28,427.089996,427.670013,422.290009,426.049988,104705800.0,0.0,0.0,0.000399